CREATE TABLE Account(id INTEGER NOT NULL primary key autoincrement, Added DATETIME NOT NULL, Updated DATETIME NOT NULL,
Password	VARCHAR(254) NOT NULL,
Role	VARCHAR(25) NOT NULL,
Email	VARCHAR(254) NOT NULL, CONSTRAINT UC_Email UNIQUE (Email));
