CREATE TABLE genSpringMSSQLTest.dbo.Sheet2(id BIGINT IDENTITY(1, 1) PRIMARY KEY,
Created DATETIME NOT NULL,
Lastmod DATETIME NOT NULL,
DateField	DATETIME NOT NULL,
IntegerField	INTEGER NOT NULL,
Text	VARCHAR(21) NOT NULL,
DecimalField	REAL);
