CREATE TABLE genSpringMSSQLTest.dbo.Sheet1(id BIGINT IDENTITY(1, 1) PRIMARY KEY,
Created DATETIME NOT NULL,
Lastmod DATETIME NOT NULL,
IntField	INTEGER NOT NULL,
DateField	DATETIME,
Text	VARCHAR(7),
DecimalField	REAL);
