CREATE TABLE genSpringMSSQLTest.dbo.Sheet2(id BIGINT IDENTITY(1, 1) PRIMARY KEY, Created DATETIME NOT NULL, Lastmod DATETIME NOT NULL,
Integer	INTEGER NOT NULL,
Decimal	REAL,
Text	VARCHAR(21) NOT NULL,
Date	DATETIME NOT NULL);
