CREATE TABLE genSpringMSSQLTest.dbo.Sheet1(id BIGINT IDENTITY(1, 1) PRIMARY KEY, Created DATETIME NOT NULL, Lastmod DATETIME NOT NULL,
Decimal	REAL,
Text	VARCHAR(7),
IntField	INTEGER NOT NULL,
Date	DATETIME);
