CREATE TABLE Watchlist.Networks(id BIGINT NOT NULL primary key auto_increment,
`Site`	VARCHAR(28) COMMENT 'len=28' NOT NULL,
`TivoShortName`	VARCHAR(10) COMMENT 'len=10',
`ShowsInTivoNpl`	INTEGER,
`StandardWait`	VARCHAR(17) COMMENT 'len=17',
`Persistance`	VARCHAR(70) COMMENT 'len=70',
`RemembersPlaceInEpisode`	VARCHAR(57) COMMENT 'len=57',
`RemembersWatchedEpisodes`	VARCHAR(35) COMMENT 'len=35',
`HasWatchList`	VARCHAR(46) COMMENT 'len=46',
`FreeWithTwcId`	VARCHAR(57) COMMENT 'len=57',
`HasDirectBuyOption`	VARCHAR(82) COMMENT 'len=82',
`Commercials`	VARCHAR(68) COMMENT 'len=68',
`ICanOta`	VARCHAR(63) COMMENT 'len=63',
`WebInterface`	VARCHAR(56) COMMENT 'len=56',
`AndroidApp`	VARCHAR(1) COMMENT 'len=1',
`RokuApp`	VARCHAR(97) COMMENT 'len=97',
`TivoApp`	VARCHAR(61) COMMENT 'len=61',
`FireApp`	VARCHAR(56) COMMENT 'len=56',
`IptvService`	VARCHAR(214) COMMENT 'len=214',
`OnHulu`	VARCHAR(14) COMMENT 'len=14',
`Comment`	VARCHAR(458) COMMENT 'len=458');
