CREATE TABLE Networks(id INTEGER NOT NULL primary key autoincrement,
Site	VARCHAR(28) NOT NULL,
TivoShortName	VARCHAR(10),
ShowsInTivoNpl	INTEGER,
StandardWait	VARCHAR(17),
Persistance	VARCHAR(70),
RemembersPlaceInEpisode	VARCHAR(57),
RemembersWatchedEpisodes	VARCHAR(35),
HasWatchList	VARCHAR(46),
FreeWithTwcId	VARCHAR(57),
HasDirectBuyOption	VARCHAR(82),
Commercials	VARCHAR(68),
ICanOta	VARCHAR(63),
WebInterface	VARCHAR(56),
AndroidApp	VARCHAR(1),
RokuApp	VARCHAR(97),
TivoApp	VARCHAR(61),
FireApp	VARCHAR(56),
IptvService	VARCHAR(214),
OnHulu	VARCHAR(14),
Comment	VARCHAR(458));
