CREATE TABLE Watchlist.Ota(id BIGINT NOT NULL primary key auto_increment,
`Userid`	BIGINT,
`ChannelNumberChannelNameIncluded`	VARCHAR(18) COMMENT 'len=18',
`Chan`	INTEGER,
`SubChan`	INTEGER,
`Station`	VARCHAR(5) COMMENT 'len=5',
`Off`	VARCHAR(5) COMMENT 'len=5',
`Enabled`	VARCHAR(3) COMMENT 'len=3',
`ChannelNumber`	VARCHAR(4) COMMENT 'len=4',
`ChannelName`	VARCHAR(10) COMMENT 'len=10',
`Freq`	INTEGER,
`MyTivoAvgStrength`	INTEGER,
`AtticAnt`	INTEGER,
`LangField`	VARCHAR(2) COMMENT 'len=2',
`Rez`	VARCHAR(5) COMMENT 'len=5',
`Comments`	VARCHAR(31) COMMENT 'len=31',
`Network`	VARCHAR(15) COMMENT 'len=15',
`TvFoolChan`	REAL,
`TvFoolEstSignal`	VARCHAR(5) COMMENT 'len=5',
`RecommendedAntenna`	VARCHAR(41) COMMENT 'len=41',
`Direction`	VARCHAR(4) COMMENT 'len=4',
`Listed`	BOOLEAN,
`FccInfo`	VARCHAR(10) COMMENT 'len=10',
`WatchableTivo`	VARCHAR(4) COMMENT 'len=4',
`WatchableTablo`	VARCHAR(7) COMMENT 'len=7',
CONSTRAINT FK_Ota_Userid FOREIGN KEY (Userid)    REFERENCES Watchlist.Account(Id));
