CREATE TABLE Ota(id INTEGER NOT NULL primary key autoincrement,
Userid	INTEGER,
ChannelNumberChannelNameIncluded	VARCHAR(18),
Chan	INTEGER,
SubChan	INTEGER,
Station	VARCHAR(5),
Off	VARCHAR(5),
Enabled	VARCHAR(3),
ChannelNumber	VARCHAR(4),
ChannelName	VARCHAR(10),
Freq	INTEGER,
MyTivoAvgStrength	INTEGER,
AtticAnt	INTEGER,
LangField	VARCHAR(2),
Rez	VARCHAR(5),
Comments	VARCHAR(31),
Network	VARCHAR(15),
TvFoolChan	REAL,
TvFoolEstSignal	VARCHAR(5),
RecommendedAntenna	VARCHAR(41),
Direction	VARCHAR(4),
Listed	INTEGER,
FccInfo	VARCHAR(10),
WatchableTivo	VARCHAR(4),
WatchableTablo	VARCHAR(7),
CONSTRAINT FK_Ota_Userid FOREIGN KEY (Userid)    REFERENCES Account(Id));
