CREATE TABLE Ota(id INTEGER NOT NULL primary key autoincrement,
Rez	VARCHAR(5),
AtticAnt	INTEGER,
TvFoolEstSignal	VARCHAR(5),
Direction	VARCHAR(4),
Chan	INTEGER,
WatchableTivo	VARCHAR(4),
Network	VARCHAR(15),
Station	VARCHAR(5),
RecommendedAntenna	VARCHAR(41),
Comments	VARCHAR(31),
Enabled	VARCHAR(3),
Lang	VARCHAR(2),
ChannelNumber	VARCHAR(4),
SubChan	INTEGER,
TvFoolChan	REAL,
Userid	INTEGER,
Off	VARCHAR(5),
MyTivoAvgStrength	INTEGER,
Listed	INTEGER,
FccInfo	VARCHAR(10),
ChannelNumberChannelNameIncluded	VARCHAR(18),
ChannelName	VARCHAR(10),
Freq	INTEGER,
WatchableTablo	VARCHAR(7),
FccInfoLink	VARCHAR(6),    CONSTRAINT FK_Ota_Userid FOREIGN KEY (Userid)    REFERENCES Account(id));
