CREATE TABLE Watchlist.RoamioSp(id BIGINT NOT NULL primary key auto_increment,
`Userid`	BIGINT,
`Priority`	INTEGER NOT NULL,
`Show`	VARCHAR(60) COMMENT 'len=60',
`Include`	VARCHAR(8) COMMENT 'len=8',
`Season`	INTEGER,
`Channel`	VARCHAR(14) COMMENT 'len=14',
`Record`	VARCHAR(13) COMMENT 'len=13',
`Keep`	VARCHAR(7) COMMENT 'len=7',
`Num`	INTEGER,
`Start`	INTEGER,
`End`	INTEGER,
CONSTRAINT FK_RoamioSp_Userid FOREIGN KEY (Userid)    REFERENCES Watchlist.Account(Id));
