CREATE TABLE RoamioTodo(id INTEGER NOT NULL primary key autoincrement,
Userid	INTEGER,
DateField	DATETIME NOT NULL,
Channel	VARCHAR(15),
Duration	VARCHAR(4),
ShowTrimmed	VARCHAR(47),
ShowName	VARCHAR(48),
EpisodeName	VARCHAR(59),
Ep	VARCHAR(50),
CONSTRAINT FK_RoamioTodo_Userid FOREIGN KEY (Userid)    REFERENCES Account(Id));
