CREATE TABLE RoamioNpl(id INTEGER NOT NULL primary key autoincrement,
SortableDate	BIGINT,
RowInShows	INTEGER,
Episode	VARCHAR(10),
BitrateMbps	INTEGER,
Isnew	REAL,
Title	VARCHAR(76),
Userid	INTEGER,
SizeGb	INTEGER,
Date	REAL,
Channel	VARCHAR(16),
Seriesep	VARCHAR(10),
Show	VARCHAR(73) NOT NULL,
Duration	REAL,
Watchedtime	INTEGER,    CONSTRAINT FK_RoamioNpl_Userid FOREIGN KEY (Userid)    REFERENCES Account(id));
