CREATE TABLE RoamioNpl(id INTEGER NOT NULL primary key autoincrement,
Userid	INTEGER,
Show	VARCHAR(73) NOT NULL,
Episode	VARCHAR(10),
Title	VARCHAR(76),
DateField	REAL,
SortableDate	BIGINT,
Channel	VARCHAR(16),
Duration	REAL,
SizeGb	INTEGER,
BitrateMbps	INTEGER,
Watchedtime	INTEGER,
Isnew	REAL,
Seriesep	VARCHAR(10),
RowInShows	INTEGER,
CONSTRAINT FK_RoamioNpl_Userid FOREIGN KEY (Userid)    REFERENCES Account(Id));
