CREATE TABLE Watchlist.RoamioNpl(id BIGINT NOT NULL primary key auto_increment,
`Userid`	BIGINT,
`Show`	VARCHAR(73) COMMENT 'len=73' NOT NULL,
`Episode`	VARCHAR(10) COMMENT 'len=10',
`Title`	VARCHAR(76) COMMENT 'len=76',
`DateField`	REAL,
`SortableDate`	BIGINT,
`Channel`	VARCHAR(16) COMMENT 'len=16',
`Duration`	REAL,
`SizeGb`	INTEGER,
`BitrateMbps`	INTEGER,
`Watchedtime`	INTEGER,
`Isnew`	REAL,
`Seriesep`	VARCHAR(10) COMMENT 'len=10',
`RowInShows`	INTEGER,
CONSTRAINT FK_RoamioNpl_Userid FOREIGN KEY (Userid)    REFERENCES Watchlist.Account(Id));
