CREATE TABLE RoamioSp(id INTEGER NOT NULL primary key autoincrement,
Userid	INTEGER,
Priority	INTEGER NOT NULL,
Show	VARCHAR(60),
Include	VARCHAR(8),
Season	INTEGER,
Channel	VARCHAR(14),
Record	VARCHAR(13),
Keep	VARCHAR(7),
Num	INTEGER,
Start	INTEGER,
End	INTEGER,
CONSTRAINT FK_RoamioSp_Userid FOREIGN KEY (Userid)    REFERENCES Account(Id));
