CREATE TABLE Watchlist.RoamioTodo(id BIGINT NOT NULL primary key auto_increment,
`Userid`	BIGINT,
`DateField`	DATETIME NOT NULL,
`Channel`	VARCHAR(15) COMMENT 'len=15',
`Duration`	VARCHAR(4) COMMENT 'len=4',
`ShowTrimmed`	VARCHAR(47) COMMENT 'len=47',
`ShowName`	VARCHAR(48) COMMENT 'len=48',
`EpisodeName`	VARCHAR(59) COMMENT 'len=59',
`Ep`	VARCHAR(50) COMMENT 'len=50',
CONSTRAINT FK_RoamioTodo_Userid FOREIGN KEY (Userid)    REFERENCES Watchlist.Account(Id));
