CREATE TABLE ShowsUser(id INTEGER NOT NULL primary key autoincrement,
LastWatched	VARCHAR(10) NOT NULL,
BestExperience	VARCHAR(17),
Comment	VARCHAR(187),
Imdb	VARCHAR(2),
Ota	VARCHAR(1),
Userid	INTEGER,
ShowsId	INTEGER,
Diff	VARCHAR(3),
InShowRssAs	VARCHAR(47),
TabloLink	VARCHAR(6),
InRokuFeed	VARCHAR(1),
JustWatch	VARCHAR(2),
CONSTRAINT FK_ShowsUser_ShowsId FOREIGN KEY (ShowsId)    REFERENCES Shows(Id),
CONSTRAINT FK_ShowsUser_Userid FOREIGN KEY (Userid)    REFERENCES Account(Id));
