CREATE TABLE Shows(id INTEGER NOT NULL primary key autoincrement,
EpguidesShowName	VARCHAR(47) NOT NULL,
LastShow	VARCHAR(10),
Network	VARCHAR(14),
TivoName	VARCHAR(47),
Status	VARCHAR(65),
InCanceledAs	VARCHAR(47),
Cancelled	VARCHAR(65),
Premiere	VARCHAR(65),
PremiereDate	DATETIME);
