CREATE TABLE Shows(id INTEGER NOT NULL primary key autoincrement,
EpguidesShowName	VARCHAR(47) NOT NULL,
LastShow	VARCHAR(10),
Network	VARCHAR(14),
TivoName	VARCHAR(47),
Status	VARCHAR(56),
InCanceledAs	VARCHAR(47),
Cancelled	VARCHAR(56),
Premiere	VARCHAR(43),
PremiereDate	DATETIME);
